/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Balance = IDL.Nat;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Asset = IDL.Variant({ 'gold' : IDL.Null, 'usdc' : IDL.Null });
export const SwapQuote = IDL.Record({
  'rate' : Balance,
  'outputAsset' : Asset,
  'inputAsset' : Asset,
  'inputAmount' : Balance,
  'outputAmount' : Balance,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'depositUsdc' : IDL.Func([Balance], [], []),
  'getAllBalances' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Principal,
            IDL.Record({ 'gold' : Balance, 'usdc' : Balance }),
          )
        ),
      ],
      ['query'],
    ),
  'getBalance' : IDL.Func(
      [],
      [IDL.Record({ 'gold' : Balance, 'usdc' : Balance })],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getQuote' : IDL.Func([], [SwapQuote], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'swapUsdcForGold' : IDL.Func([Balance], [], []),
  'updateRate' : IDL.Func([Balance], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Balance = IDL.Nat;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Asset = IDL.Variant({ 'gold' : IDL.Null, 'usdc' : IDL.Null });
  const SwapQuote = IDL.Record({
    'rate' : Balance,
    'outputAsset' : Asset,
    'inputAsset' : Asset,
    'inputAmount' : Balance,
    'outputAmount' : Balance,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'depositUsdc' : IDL.Func([Balance], [], []),
    'getAllBalances' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Principal,
              IDL.Record({ 'gold' : Balance, 'usdc' : Balance }),
            )
          ),
        ],
        ['query'],
      ),
    'getBalance' : IDL.Func(
        [],
        [IDL.Record({ 'gold' : Balance, 'usdc' : Balance })],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getQuote' : IDL.Func([], [SwapQuote], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'swapUsdcForGold' : IDL.Func([Balance], [], []),
    'updateRate' : IDL.Func([Balance], [], []),
  });
};

export const init = ({ IDL }) => { return []; };